version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlcontainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cicdtest
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - db_data:/var/lib/mysql

  nodeapp:
    build: .
    container_name: nodeappcontainer
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: cicdtest
      DB_PORT: 3306
    ports:
      - "3333:3333"
    depends_on:
      - mysql

volumes:
 db_data:
